[versions]
# Kotlin
kotlin = "2.2.0" # https://kotlinlang.org/

# Testing - JUnit5
junit-bom = "5.13.4" # https://junit.org/junit5/
junit-legacy = "4.13.2" # https://junit.org/junit4/

# KtLint
ktlint-core = "1.7.1" # https://pinterest.github.io/ktlint/

# Gradle plugins
ktlint-gradle = "13.0.0" # https://github.com/JLLeitschuh/ktlint-gradle
intellij-platform = "2.7.1" # https://github.com/JetBrains/intellij-platform-gradle-plugin

# IDE versions
sinceBuildIdea = "213.7172" # https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
verificationIdea = "2023.2.7" # https://plugins.jetbrains.com/docs/intellij/plugin-compatibility.html
jvmTarget = "21" # https://docs.oracle.com/en/java/javase/21/

[libraries]
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit-bom" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit-bom" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-bom" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-bom" }

junit-legacy = { group = "junit", name = "junit", version.ref = "junit-legacy" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

ktlint-gradle-plugin = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }

intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform" }
